### ISSUE TITLE
Space in path name

### ISSUE THREAD

**Issue by thisischrisj** [t32k/grunt-kss#29]
This has been raised before (issue #5 and #8) and was fixed in V1.0.0 but I'm having this issue again using version V2.0.0. For a project that exists in /Websites/My Projects/Project/...

The task produces the error:

```
Running "kss:dist" (kss) task
>> kss-node 'dev/scss/main.scss' 'styleguide'
>> Error: Command failed: 
>> module.js:340
>>     throw err;
>>           ^
>> Error: Cannot find module '/Websites/My'
>>     at Function.Module._resolveFilename (module.js:338:15)
>>     at Function.Module._load (module.js:280:25)
>>     at Function.Module.runMain (module.js:497:10)
>>     at startup (node.js:119:16)
>>     at node.js:929:3
>> Code: 
>> module.js:340
>>     throw err;
>>           ^
>> Error: Cannot find module '/Websites/My'
>>     at Function.Module._resolveFilename (module.js:338:15)
>>     at Function.Module._load (module.js:280:25)
>>     at Function.Module.runMain (module.js:497:10)
>>     at startup (node.js:119:16)
>>     at node.js:929:3
```

**Comment by techsoldaten** [comment]
I was able to solve this by adding the following to node_modules/grunt-kss/tasks/kss.jss:

```
    var kssCmd = ['node'],
      realPath = path.dirname(__filename).replace(/tasks$/g, '').replace(/ /g,'\\ '),
      dest = process.cwd();
```

Line 21 of the file. Add the additional replace at the end of the string to compensate for spaces in filenames on OSX.

**Comment by kimegede** [comment]
Using ``"grunt-kss": "^2.0.0"``` and still happends here.

**Comment by turnavies** [comment]
Also experiencing this issue with 2.0.0

**Comment by kimegede** [comment]
Sadly not maintained I guess: https://github.com/t32k/grunt-kss/issues/37

**Comment by idmontie** [comment]
I believe I have a fix for this in #42. I'm on Windows and this was patch was able to get grunt-kss to work with folders that have spaces in their names.
